name: Execute Code

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node container
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - run: npm install ts-node typescript
        name: Installing packages
      
      - run: tsc
        name: Building Javascript
        
      - run: npx node test/index.js
        name: Execute Javascript 

      - run: npx ts-node test/index.ts
        name: Execute Typescript
