name: Run test file

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node container
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - run: npm install ts-node
        name: Installing packages
      
      - run: npx ts-node test/index.ts
        name: Execute test file
